apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gere-residuo-sc
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
  cachingmode: None
  fstype: ext4