apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-notificacao-ms-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: agenda-notificacao-ms-template
      labels:
        deployment: agenda.notificacao.ms
    spec:
      containers:
        - name: agenda-notificacao-ms-container
          image: ferrarezzodev/gere-residuo-kubernetes:agenda.notificacao.ms.fix.stable.cachecontrol
          # Porta atribuida dinamicamente pelo Eureka
#          ports:
#            - containerPort: 5050
          env:
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: agenda-notificacao-ms-secret
                  key: MAIL_HOST
            - name: MAIL_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: agenda-notificacao-ms-secret
                  key: MAIL_SMTP_PORT
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: agenda-notificacao-ms-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agenda-notificacao-ms-secret
                  key: MAIL_PASSWORD
            - name: ORACLE_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: agenda-notificacao-ms-secret
                  key: ORACLE_DATASOURCE_URL
            - name: ORACLE_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: agenda-notificacao-ms-secret
                  key: ORACLE_DATASOURCE_USERNAME
            - name: ORACLE_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agenda-notificacao-ms-secret
                  key: ORACLE_DATASOURCE_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 75m
  selector:
    matchLabels:
      deployment: agenda.notificacao.ms
