apiVersion: v1
kind: Secret
metadata:
  name: agenda-notificacao-ms-secret
type: Opaque
data:
  MAIL_HOST: c2FuZGJveC5zbXRwLm1haWx0cmFwLmlv
  MAIL_SMTP_PORT: NTg3
  MAIL_USERNAME: NDBjZGFlODBkZmZjODc=
  MAIL_PASSWORD: YzI0NWRiYzMwNDkwZDY=
  ORACLE_DATASOURCE_URL: amRiYzpvcmFjbGU6dGhpbjpAb3JhY2xlLXN0czoxNTIxOlhF
  ORACLE_DATASOURCE_USERNAME: YWdlbmRhX25vdGlmaWNhY2Fv
  ORACLE_DATASOURCE_PASSWORD: MTcxMjA0