apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-notificacao-ms-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: agenda-notificacao-ms-template
      labels:
        deployment: agenda.notificacao.ms
    spec:
      containers:
        - name: agenda-notificacao-ms-container
          image: ferrarezzodev/gere-residuo-kubernetes:agenda.notificacao.ms.fix
          # Porta atribuida dinamicamente pelo Eureka
#          ports:
#            - containerPort: 5050
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 75m
  selector:
    matchLabels:
      deployment: agenda.notificacao.ms
