CREATE SEQUENCE T_AGENDA_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE T_NOTIFICACAO_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE T_AGENDA (
            id INTEGER DEFAULT T_AGENDA_SEQUENCE.NEXTVAL NOT NULL,
            id_caminhao NUMBER(5) NOT NULL,
            id_motorista NUMBER(5) NOT NULL,
            id_bairro NUMBER(5) NOT NULL,
            dia_coleta DATE NOT NULL,
            tipo_residuo VARCHAR2(20) DEFAULT 'GERAL',
            status_coleta VARCHAR2(20) DEFAULT 'EM_ANDAMENTO',
            peso_coleta_kg NUMBER(10) DEFAULT 0
        );

        ALTER TABLE T_AGENDA
            ADD CONSTRAINT PK_T_AGENDA PRIMARY KEY (id);


CREATE TABLE T_NOTIFICACAO (
    id INTEGER DEFAULT T_NOTIFICACAO_SEQUENCE.NEXTVAL NOT NULL,
    id_agenda NUMBER(5) NOT NULL,
    nome_morador VARCHAR2(30) NOT NULL,
    dia_coleta DATE NOT NULL,
    tipo_residuo VARCHAR2(20) DEFAULT 'GERAL',
    email_morador VARCHAR2(60) NOT NULL,
    prc_coleta_bairro NUMBER(3) NOT NULL
    );

    ALTER TABLE T_NOTIFICACAO
        ADD CONSTRAINT PK_T_NOTIFICACAO PRIMARY KEY (id);

    ALTER TABLE T_NOTIFICACAO ADD CONSTRAINT CK_T_NOTIFICACAO_EMAIL_MORADOR
        CHECK (email_morador LIKE '%_@__%.__%');


ALTER TABLE T_AGENDA ADD CONSTRAINT FK_T_AGENDA_T_CAMINHAO FOREIGN KEY (id_caminhao) REFERENCES motorista_caminhao.T_CAMINHAO (id);
ALTER TABLE T_AGENDA ADD CONSTRAINT FK_T_AGENDA_T_MOTORISTA FOREIGN KEY (id_motorista) REFERENCES motorista_caminhao.T_MOTORISTA (id);
ALTER TABLE T_AGENDA ADD CONSTRAINT FK_T_AGENDA_T_BAIRRO FOREIGN KEY (id_bairro) REFERENCES morador_bairro.T_BAIRRO (id);
ALTER TABLE T_NOTIFICACAO ADD CONSTRAINT FK_T_NOTIFICACAO_T_AGENDA FOREIGN KEY (id_agenda) REFERENCES T_AGENDA (id);