apiVersion: v1
kind: Service
metadata:
  name: api-gateway-dp
spec:
  type: LoadBalancer
  selector:
    deployment: api.gateway
  ports:
    - port: 5051
      targetPort: 5051
      nodePort: 30000